/* Plugin Template generated by Pawn Studio */

#include <sourcemod>
#include <sdktools>

public Plugin:myinfo = 
{
	name = "Print team names.",
	author = "Recon",
	description = "Prints team indicies and names.",
	version = "1.0",
	url = "<- URL ->"
}

public OnPluginStart()
{
	RegServerCmd("sm_teaminfo", Command_PrintTeamNames);
}

public Action:Command_PrintTeamNames(args)
{
	decl String:name[50];
	
	for (new i = 0; i < 4; i++)
	{
		GetTeamName(i, name, sizeof(name));		
		PrintToServer("Team index %i - Team name %s", i, name);
	}
}